(()=>{
const KEY='cryptoPortfolioV1';
let state,seed,labels,assets,exchanges;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=2)=>Number.isFinite(+n)?(+n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const fmtQty=n=>Number.isFinite(+n)?(+n).toLocaleString('en-US',{maximumFractionDigits:8}):'—';
const signed=n=>`${n>=0?'+':''}${fmt(n)} U`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const L=(group,key,fallback='')=>labels?.[group]?.[key]??fallback??key;
const clone=o=>JSON.parse(JSON.stringify(o));
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function loadAndMigrate(){let existing=null;try{existing=JSON.parse(localStorage.getItem(KEY));}catch{}if(!existing){state=clone(seed);state.dataVersion=seed.dataVersion;save();return;}state=existing;const v=+state.dataVersion||1;if(v<3){state.plans=clone(seed.plans);state.strategySettlements=clone(seed.strategySettlements);state.fxTwdPerUsd=(+state.fxTwdPerUsd===31.6||!state.fxTwdPerUsd)?seed.fxTwdPerUsd:state.fxTwdPerUsd;state.prices=state.prices||{};state.priceMeta=state.priceMeta||{};for(const a of seed.assets){if(!state.priceMeta[a])state.prices[a]=seed.prices[a];}state.dataVersion=3;save();}state.plans=state.plans||clone(seed.plans);state.strategySettlements=state.strategySettlements||clone(seed.strategySettlements);state.prices={...seed.prices,...(state.prices||{})};state.priceMeta=state.priceMeta||{};}
function strategyRealized(){return (state.strategySettlements||[]).reduce((s,x)=>s+(+x.realized||0),0);}
function calc(){const pos={},history=[];let realized=0;for(const t of [...state.transactions].sort((a,b)=>a.id-b.id)){const key=t.warehouse+'|'+t.asset,p=pos[key]||{warehouse:t.warehouse,asset:t.asset,qty:0,cost:0,realized:0};const beforeQty=p.qty,beforeCost=p.cost;let tradeRealized=0,costRemoved=0;if(t.side==='買入'){p.qty+=(+t.qty||0)-((t.feeAsset===t.asset)?(+t.feeQty||0):0);p.cost+=+t.amount||0;}else{const proceeds=(+t.amount||0)-((t.feeAsset==='USDT')?(+t.feeQty||0):0);costRemoved=(t.costAdjustment!==null&&t.costAdjustment!==undefined&&t.costAdjustment!=='')?+t.costAdjustment:(beforeQty>0?(+t.qty||0)*(beforeCost/beforeQty):0);tradeRealized=proceeds-costRemoved;realized+=tradeRealized;p.realized+=tradeRealized;if(t.reset){p.qty=0;p.cost=0;}else{p.qty=Math.max(0,beforeQty-(+t.qty||0));p.cost=Math.max(0,beforeCost-costRemoved);}}pos[key]=p;history.push({...t,beforeQty,beforeCost,afterQty:p.qty,afterCost:p.cost,tradeRealized,costRemoved});}return{positions:Object.values(pos),history,realized};}
const mv=p=>p.qty*(+state.prices[p.asset]||0);
function kpi(label,value,num){return `<div class="card kpi"><div class="label">${esc(label)}</div><div class="value ${num>0?'good':num<0?'bad':''}">${value}</div></div>`;}
function holdingTable(ps,showWh=false){return `<div class="table-wrap"><table><thead><tr>${showWh?`<th>${L('holdings','warehouse','倉位')}</th>`:''}<th>${L('holdings','asset','資產')}</th><th>${L('holdings','quantity','數量')}</th><th>${L('holdings','cost','成本U')}</th><th>${L('holdings','avgCost','均價U')}</th><th>${L('holdings','price','現價U')}</th><th>${L('holdings','marketValue','市值U')}</th><th>${L('holdings','unrealized','未實現')}</th></tr></thead><tbody>${ps.length?ps.map(p=>{const v=mv(p),u=v-p.cost;return `<tr>${showWh?`<td>${p.warehouse}</td>`:''}<td>${p.asset}</td><td>${fmtQty(p.qty)}</td><td>${fmt(p.cost)}</td><td>${p.qty?fmt(p.cost/p.qty):'—'}</td><td>${fmt(state.prices[p.asset]||0)}</td><td>${fmt(v)}</td><td class="${u>=0?'good':'bad'}">${signed(u)}</td></tr>`}).join(''):`<tr><td colspan="${showWh?8:7}" class="muted">尚無持倉</td></tr>`}</tbody></table></div>`;}
function warehouseFold(w,ps){const cost=ps.reduce((s,p)=>s+p.cost,0),market=ps.reduce((s,p)=>s+mv(p),0);return `<details class="fold-card" open><summary><span class="fold-title"><h2>${esc(w)}</h2><span class="fold-meta">${fmt(cost)} U → ${fmt(market)} U</span></span></summary><div class="fold-body">${holdingTable(ps)}</div></details>`;}
function renderDashboard(){const c=calc(),active=c.positions.filter(p=>p.qty>1e-12||p.cost>1e-9),market=active.reduce((s,p)=>s+mv(p),0),cost=active.reduce((s,p)=>s+p.cost,0),unreal=market-cost,spot=c.realized,strategy=strategyRealized(),realized=spot+strategy,total=unreal+realized;q('#dashboard').innerHTML=`<div class="grid">${kpi(L('dashboard','marketValue','目前市值'),fmt(market)+' U')}${kpi(L('dashboard','holdingCost','持倉成本'),fmt(cost)+' U')}${kpi(L('dashboard','unrealizedPnl','未實現損益'),signed(unreal),unreal)}${kpi(L('dashboard','realizedPnl','已實現損益'),signed(realized),realized)}${kpi(L('dashboard','totalPnl','總損益'),signed(total),total)}</div><div class="notice section">${L('dashboard','realizedBreakdown','已實現損益 = 現貨已實現 + 策略已實現')}：${signed(spot)} + ${signed(strategy)} = ${signed(realized)}</div><div class="split section">${warehouseFold('第一倉',active.filter(p=>p.warehouse==='第一倉'))}${warehouseFold('第二倉',active.filter(p=>p.warehouse==='第二倉'))}</div><div class="card section"><h2>${L('dashboard','allHoldings','全部持倉')}</h2>${holdingTable(active,true)}</div>`;}
function allocationBar(w,ps){const target=Object.values(state.plans[w]||{}).reduce((s,x)=>s+(+x||0),0),invested=ps.reduce((s,p)=>s+p.cost,0),pct=target?invested/target*100:0,active=ps.filter(p=>p.cost>0),totalInvested=active.reduce((s,p)=>s+p.cost,0)||1;const segs=active.map(p=>`<span class="allocation-seg asset-${p.asset}" style="width:${p.cost/totalInvested*100}%" title="${p.asset}: ${fmt(p.cost)} U"></span>`).join('');const legend=active.map(p=>`<span class="legend-item"><i class="legend-dot asset-${p.asset}"></i>${p.asset} ${fmt(p.cost)} U (${fmt(p.cost/totalInvested*100,1)}%)</span>`).join('');return `<div class="allocation"><div class="allocation-top"><span>${L('plans','allocation','目前投入比例')}</span><span class="allocation-number">${L('plans','investedTotal','已投入')} ${fmt(invested)} / ${L('plans','targetTotal','目標')} ${fmt(target)} U <span class="pct ${pct>100?'over':''}">${fmt(pct,1)}%</span></span></div><div class="allocation-bar">${segs}</div><div class="allocation-legend">${legend||'<span>尚無投入</span>'}</div></div>`;}
function renderPlans(){const c=calc();q('#plans').innerHTML=['第一倉','第二倉'].map(w=>{const ps=c.positions.filter(p=>p.warehouse===w),targetTotal=Object.values(state.plans[w]||{}).reduce((s,x)=>s+(+x||0),0),invested=ps.reduce((s,p)=>s+p.cost,0),pct=targetTotal?invested/targetTotal*100:0;return `<details class="fold-card section" open><summary><span class="fold-title"><h2>${w}</h2><span class="fold-meta">${fmt(invested)} / ${fmt(targetTotal)} U · <span class="${pct>100?'over':''}">${fmt(pct,1)}%</span></span></span></summary><div class="fold-body">${allocationBar(w,ps)}<div class="table-wrap"><table><thead><tr><th>${L('holdings','asset','資產')}</th><th>${L('plans','target','目標U')}</th><th>${L('plans','invested','目前投入U')}</th><th>${L('plans','completion','完成率')}</th></tr></thead><tbody>${assets.map(a=>{const target=+state.plans[w]?.[a]||0,p=ps.find(x=>x.asset===a),cost=p?.cost||0,r=target?cost/target*100:0;return `<tr><td>${a}</td><td><input class="plan-input" data-plan="${w}|${a}" type="number" step="any" value="${target}"></td><td>${fmt(cost)}</td><td><div class="progress"><i style="width:${Math.min(100,r)}%"></i></div><span class="subtle ${r>100?'over':''}">${target?fmt(r,1)+'%':'—'}</span></td></tr>`}).join('')}</tbody></table></div></div></details>`}).join('');qa('[data-plan]').forEach(i=>i.onchange=()=>{const[w,a]=i.dataset.plan.split('|');state.plans[w][a]=+i.value||0;save();renderAll();switchTab('plans');});}
function input(name,label,type,val,extra=''){return `<div class="field"><label>${esc(label)}</label><input name="${name}" type="${type}" value="${esc(val)}" ${extra}></div>`;}
function select(name,label,opts,val){return `<div class="field"><label>${esc(label)}</label><select name="${name}">${opts.map(o=>`<option value="${esc(o)}" ${o===val?'selected':''}>${esc(o||'—')}</option>`).join('')}</select></div>`;}
function formHtml(t={}){const T=labels.transactions||{};return `<input type="hidden" name="id" value="${t.id||''}">${select('warehouse',T.warehouse||'倉位',['第一倉','第二倉'],t.warehouse||'第一倉')}${select('exchange',T.exchange||'交易所',exchanges,t.exchange||'幣安')}${input('date',T.date||'日期','date',t.date||new Date().toISOString().slice(0,10))}${select('side',T.side||'買賣',['買入','賣出'],t.side||'買入')}${select('asset',T.asset||'幣種',assets,t.asset||'BTC')}${input('price',T.price||'成交價 U','number',t.price||'','step="any"')}${input('qty',T.quantity||'數量','number',t.qty||'','step="any"')}${input('amount',T.amount||'交易金額 U','number',t.amount||'','step="any"')}${select('feeAsset',T.feeAsset||'手續費幣種',['',...assets,'USDT'],t.feeAsset||'')}${input('feeQty',T.feeQuantity||'手續費數量','number',t.feeQty||0,'step="any"')}${input('costAdjustment',T.costAdjustment||'賣出成本校正 U','number',t.costAdjustment??'','step="any"')}<div class="field"><label>${T.reset||'清倉'}</label><select name="reset"><option value="false" ${!t.reset?'selected':''}>否</option><option value="true" ${t.reset?'selected':''}>是</option></select></div><div class="field full"><label>${T.note||'備註'}</label><textarea name="note">${esc(t.note||'')}</textarea></div><div class="full toolbar"><button class="btn primary" type="submit">${t.id?(T.saveEdit||'儲存修改'):(T.save||'新增交易')}</button><button class="btn" type="button" id="cancelEdit">${T.clear||'清空表單'}</button></div>`;}
function historyTable(h){const T=labels.transactions||{};return `<div class="table-wrap"><table><thead><tr><th>#</th><th>${T.warehouse||'倉位'}</th><th>${T.date||'日期'}</th><th>${T.side||'買賣'}</th><th>${T.asset||'幣種'}</th><th>${T.quantity||'數量'}</th><th>${T.amount||'交易金額 U'}</th><th>${T.beforeCost||'交易前成本'}</th><th>${T.afterCost||'交易後成本'}</th><th>${T.tradeRealized||'本筆已實現'}</th><th>${T.action||'操作'}</th></tr></thead><tbody>${[...h].reverse().map(t=>`<tr><td>${t.id}</td><td>${t.warehouse}</td><td>${t.date}</td><td><span class="chip">${t.side}</span></td><td>${t.asset}</td><td>${fmtQty(t.qty)}</td><td>${fmt(t.amount)}</td><td>${fmt(t.beforeCost)}</td><td>${fmt(t.afterCost)}</td><td class="${t.tradeRealized>0?'good':t.tradeRealized<0?'bad':''}">${t.side==='賣出'?signed(t.tradeRealized):'—'}</td><td class="row-actions"><button data-edit="${t.id}">編輯</button> <button data-del="${t.id}">刪除</button></td></tr>`).join('')}</tbody></table></div>`;}
function renderTransactions(){const c=calc();q('#transactions').innerHTML=`<div class="card"><h2>${L('transactions','formTitle','新增 / 修改交易')}</h2><form id="txForm" class="form-grid">${formHtml()}</form></div><div class="section"><div class="toolbar"><strong>${L('tabs','transactions','交易紀錄')}</strong><span class="grow"></span><span class="muted">修改任何舊交易都會依流水號重新計算</span></div>${historyTable(c.history)}</div>`;bindTx();}
function bindTx(){const f=q('#txForm');f.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f)),id=d.id?+d.id:Math.max(0,...state.transactions.map(x=>x.id))+1,obj={id,warehouse:d.warehouse,exchange:d.exchange,date:d.date,side:d.side,asset:d.asset,price:+d.price||0,qty:+d.qty||0,amount:+d.amount||0,feeAsset:d.feeAsset,feeQty:+d.feeQty||0,costAdjustment:d.costAdjustment===''?null:+d.costAdjustment,reset:d.reset==='true',note:d.note||''},i=state.transactions.findIndex(x=>x.id===id);i>=0?state.transactions[i]=obj:state.transactions.push(obj);save();renderAll();switchTab('transactions');};q('#cancelEdit').onclick=()=>renderTransactions();qa('[data-edit]').forEach(b=>b.onclick=()=>{const t=state.transactions.find(x=>x.id===+b.dataset.edit);q('#txForm').innerHTML=formHtml(t);bindTx();scrollTo({top:0,behavior:'smooth'});});qa('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('確定刪除這筆交易？後續成本會全部重算。')){state.transactions=state.transactions.filter(x=>x.id!==+b.dataset.del);save();renderAll();switchTab('transactions');}});}
function renderPrices(){q('#prices').innerHTML=`<div class="notice">${L('prices','notice','Crypto 可從 Binance 自動更新；MSTR 目前採手動價。')}</div><div class="price-grid section">${assets.map(a=>`<div class="price-box"><strong>${a}</strong><input data-price="${a}" type="number" step="any" value="${state.prices[a]??0}"><div class="subtle">${esc(state.priceMeta[a]||L('prices','manual','手動 / Excel 備援值'))}</div></div>`).join('')}</div>`;qa('[data-price]').forEach(i=>i.onchange=()=>{state.prices[i.dataset.price]=+i.value||0;state.priceMeta[i.dataset.price]='手動更新 '+new Date().toLocaleString();save();renderAll();switchTab('prices');});}
function renderBackup(){const sReal=strategyRealized();q('#backup').innerHTML=`<div class="grid">${kpi(L('backup','tradeCount','交易筆數'),String(state.transactions.length))}${kpi(L('backup','fx','匯率 TWD/USD'),fmt(state.fxTwdPerUsd,3))}${kpi(L('backup','strategyRealized','策略已結算損益'),fmt(sReal)+' U',sReal)}${kpi(L('backup','dataLocation','資料位置'),L('backup','browser','此瀏覽器'))}</div><div class="card section"><h2>${L('backup','backupTitle','資料備份')}</h2><div class="toolbar"><button class="btn primary" id="exportJson">${L('backup','export','匯出 JSON')}</button><label class="btn">${L('backup','import','匯入 JSON')}<input id="importJson" type="file" accept="application/json" hidden></label><button class="btn danger" id="resetData">${L('backup','reset','恢復 Excel 初始資料')}</button></div><div class="notice">${L('backup','notice','GitHub 只放程式碼與初始資料，不保存你後續新增的交易紀錄。')}</div></div><div class="card section"><h2>${L('backup','settings','其他設定')}</h2><div class="form-grid">${input('fx',L('backup','fx','匯率 TWD/USD'),'number',state.fxTwdPerUsd,'step="any"')}</div></div>`;q('[name=fx]').onchange=e=>{state.fxTwdPerUsd=+e.target.value||0;save();renderAll();switchTab('backup');};q('#exportJson').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='crypto-portfolio-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);};q('#importJson').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const o=JSON.parse(r.result);if(!o.transactions||!o.prices)throw 0;state=o;state.dataVersion=seed.dataVersion;save();renderAll();alert('匯入完成');}catch{alert('JSON 格式不正確');}};r.readAsText(f);};q('#resetData').onclick=()=>{if(confirm('確定恢復 Excel 初始資料？目前瀏覽器資料會被覆蓋。')){state=clone(seed);save();renderAll();}};}
async function refreshPrices(silent=false){const btn=q('#refreshPrices');if(btn){btn.disabled=true;btn.textContent='更新中…';}let failed=[];await Promise.all(assets.filter(a=>a!=='MSTR').map(async a=>{try{const r=await fetch(`https://api.binance.com/api/v3/ticker/price?symbol=${a}USDT`);if(!r.ok)throw 0;const p=+(await r.json()).price;if(p>0){state.prices[a]=p;state.priceMeta[a]='Binance '+new Date().toLocaleString();}}catch{failed.push(a);}}));save();renderAll();if(btn){btn.disabled=false;btn.textContent=L('app','refreshPrices','更新 Crypto 價格');}if(failed.length&&!silent)alert(`部分價格更新失敗：${failed.join(', ')}。可到「價格」頁手動輸入。`);}
function renderChrome(){q('#appTitle').textContent=L('app','title','Crypto Portfolio');q('#appSubtitle').textContent=L('app','subtitle','');q('#refreshPrices').textContent=L('app','refreshPrices','更新 Crypto 價格');qa('#tabs button').forEach(b=>b.textContent=L('tabs',b.dataset.tab,b.dataset.tab));}
function renderAll(){renderChrome();renderDashboard();renderTransactions();renderPlans();renderPrices();renderBackup();}
function switchTab(name){qa('.tab-pane').forEach(x=>x.classList.toggle('hidden',x.id!==name));qa('#tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));}
async function init(){try{[seed,labels]=await Promise.all([fetch('./portfolio-data.json',{cache:'no-store'}).then(r=>r.json()),fetch('./ui-labels.json',{cache:'no-store'}).then(r=>r.json())]);}catch(e){document.body.innerHTML='<div style="padding:30px;color:white">資料檔載入失敗，請重新整理。</div>';return;}assets=seed.assets;exchanges=seed.exchanges;loadAndMigrate();qa('#tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));q('#refreshPrices').onclick=()=>refreshPrices(false);renderAll();if(!sessionStorage.getItem('portfolioPriceRefreshed')){sessionStorage.setItem('portfolioPriceRefreshed','1');refreshPrices(true);}}
init();
})();
