import {reconciledPortfolio,planMetrics,marketValue} from './calculations.js?v=20260907-1140';
import {saveState,exportBackup,importBackup,resetState} from './records.js?v=20260907-1140';

const fmt=(n,d=2)=>Number.isFinite(+n)?(+n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const qty=n=>Number.isFinite(+n)?(+n).toLocaleString('en-US',{maximumFractionDigits:8}):'—';
const signed=n=>`${n>=0?'+':''}${fmt(n)} U`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const assetLabel=p=>p.label||({STABLE:'USDT/USDC',OTHER:'其他小額資產',CASH:'USDT/USDC'}[p.asset]||p.asset);
const noQtyAsset=a=>['STABLE','OTHER','CASH'].includes(a);

export function mountApp({state,seed,labels,setState}){
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const L=(g,k,f='')=>labels?.[g]?.[k]??f??k;
  const assets=state.assets||seed.assets,exchanges=state.exchanges||seed.exchanges;
  q('#appTitle').textContent=labels?.app?.title||'Crypto Portfolio';
  q('#appSubtitle').textContent=labels?.app?.subtitle||'';
  const tabNames=labels?.tabs||{};qa('#tabs [data-tab]').forEach(b=>b.textContent=tabNames[b.dataset.tab]||b.dataset.tab);
  const switchTab=name=>{qa('.tab-pane').forEach(x=>x.classList.toggle('hidden',x.id!==name));qa('#tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));};
  qa('#tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));

  function holdingTable(ps,showWh=false){
    return `<div class="table-wrap"><table><thead><tr>${showWh?'<th>倉位</th>':''}<th>資產</th><th>數量</th><th>成本U</th><th>均價U</th><th>現價U</th><th>市值U</th><th>未實現</th></tr></thead><tbody>${ps.map(p=>{const v=marketValue(p,state.prices);const known=Number.isFinite(+p.cost);const u=known?v-p.cost:null;const noQty=noQtyAsset(p.asset);return `<tr>${showWh?`<td>${p.warehouse}</td>`:''}<td>${assetLabel(p)}${p.legacy?' <span class="subtle">歷史差額</span>':''}</td><td>${noQty?'—':qty(p.qty)}</td><td>${known?fmt(p.cost):'—'}</td><td>${known&&p.qty?fmt(p.cost/p.qty):'—'}</td><td>${noQty?'—':fmt(state.prices[p.asset]||0)}</td><td>${fmt(v)}</td><td class="${u==null?'':u>=0?'good':'bad'}">${u==null?'—':signed(u)}</td></tr>`}).join('')}</tbody></table></div>`;
  }

  function holdingCards(ps){
    return `<div class="holding-grid">${ps.map(p=>{const v=marketValue(p,state.prices);const known=Number.isFinite(+p.cost);const u=known?v-p.cost:null;const noQty=noQtyAsset(p.asset);return `<div class="holding-card"><div class="holding-card-top"><strong>${assetLabel(p)}</strong>${p.legacy?'<span class="chip">歷史差額</span>':''}</div><div class="holding-value">${fmt(v)} U</div><div class="holding-meta">${noQty?'只管理金額':`數量 ${qty(p.qty)}`}${known?` · 成本 ${fmt(p.cost)} U`:''}</div>${u==null?'':`<div class="holding-pnl ${u>=0?'good':'bad'}">${signed(u)}</div>`}</div>`}).join('')}</div>`;
  }

  function fold(name,ps){const market=ps.reduce((s,p)=>s+marketValue(p,state.prices),0),knownCost=ps.reduce((s,p)=>s+(Number.isFinite(+p.cost)?+p.cost:0),0);return `<details class="fold-card" open><summary><span class="fold-title"><h2>${name}</h2><span class="fold-meta">${name==='第二倉'?'實際水庫 ':'成本 '+fmt(knownCost)+' U → '}${fmt(market)} U</span></span></summary><div class="fold-body">${holdingCards(ps)}</div></details>`;}
  function kpi(label,value,num){return `<div class="card kpi"><div class="label">${label}</div><div class="value ${num>0?'good':num<0?'bad':''}">${value}</div></div>`;}

  function renderDashboard(){
    const c=reconciledPortfolio(state),first=c.warehouses.第一倉,second=c.warehouses.第二倉;
    const reference=+c.snapshot?.referenceTotal||+c.snapshot?.totalValue||0;
    q('#dashboard').innerHTML=`<div class="grid">${kpi('目前總資產',fmt(c.displayMarket)+' U')}${kpi('可計算持倉成本',fmt(c.cost)+' U')}${kpi('可計算未實現損益',signed(c.unrealized),c.unrealized)}${kpi('已實現損益',signed(c.realized),c.realized)}${kpi('可計算總損益',signed(c.totalPnl),c.totalPnl)}</div>${c.reconciled?`<div class="notice section">2026/09/07 對帳快照 ${fmt(reference)} U 僅作基準；現在總資產依實際幣數 × 最新價格重新計算。USDT/USDC 只管理金額，其他小額資產也只保留總金額，不用數量。</div>`:''}<div class="split section">${fold('第一倉',first)}${fold('第二倉',second)}</div><div class="card section"><h2>全部持倉</h2>${holdingTable([...first,...second],true)}</div>`;
  }

  function renderPlans(){
    const c=reconciledPortfolio(state);q('#plans').innerHTML=['第一倉','第二倉'].map(w=>{const ps=w==='第一倉'?c.warehouses.第一倉:c.active.filter(p=>p.warehouse==='第二倉'),m=planMetrics(state,w,ps);return `<details class="fold-card section" open><summary><span class="fold-title"><h2>${w}</h2><span class="fold-meta">已納管 ${fmt(m.invested)} / 目標 ${fmt(m.target)} U · ${fmt(m.pct,1)}%</span></span></summary><div class="fold-body"><div class="notice">${w==='第二倉'?'第二倉歷史水庫不硬補成本；投資計畫完成率只計有交易紀錄的新增投入。':'第一倉沿用完整交易成本鏈。'}</div><div class="table-wrap"><table><thead><tr><th>資產</th><th>目標U</th><th>已納管成本U</th><th>完成率</th></tr></thead><tbody>${assets.filter(a=>!['CASH','STABLE','OTHER'].includes(a)).map(a=>{const target=+state.plans?.[w]?.[a]||0,p=ps.find(x=>x.asset===a),cost=Number.isFinite(+p?.cost)?+p.cost:0,r=target?cost/target*100:0;return `<tr><td>${a}</td><td><input class="plan-input" data-plan="${w}|${a}" type="number" step="any" value="${target}"></td><td>${fmt(cost)}</td><td>${target?fmt(r,1)+'%':'—'}</td></tr>`}).join('')}</tbody></table></div></div></details>`}).join('');
    qa('[data-plan]').forEach(i=>i.onchange=()=>{const[w,a]=i.dataset.plan.split('|');state.plans[w][a]=+i.value||0;saveState(state);renderAll();switchTab('plans');});
  }

  function txForm(t={}){const opts=(name,list,val)=>`<label>${name}<select name="${name}">${list.map(x=>`<option value="${x}" ${x===val?'selected':''}>${x}</option>`).join('')}</select></label>`;return `<input type="hidden" name="id" value="${t.id||''}">${opts('warehouse',['第一倉','第二倉'],t.warehouse||'第一倉')}${opts('exchange',exchanges,t.exchange||'幣安')}<label>date<input name="date" type="date" value="${t.date||new Date().toISOString().slice(0,10)}"></label>${opts('side',['買入','賣出'],t.side||'買入')}${opts('asset',assets.filter(a=>!['CASH','STABLE','OTHER'].includes(a)),t.asset||'BTC')}<label>price<input name="price" type="number" step="any" value="${t.price||''}"></label><label>qty<input name="qty" type="number" step="any" value="${t.qty||''}"></label><label>amount<input name="amount" type="number" step="any" value="${t.amount||''}"></label><label>feeAsset<select name="feeAsset">${['',...assets,'USDT'].map(x=>`<option value="${x}" ${x===(t.feeAsset||'')?'selected':''}>${x||'—'}</option>`).join('')}</select></label><label>feeQty<input name="feeQty" type="number" step="any" value="${t.feeQty||0}"></label><label>costAdjustment<input name="costAdjustment" type="number" step="any" value="${t.costAdjustment??''}"></label><label>reset<select name="reset"><option value="false" ${!t.reset?'selected':''}>否</option><option value="true" ${t.reset?'selected':''}>是</option></select></label><label class="full">note<textarea name="note">${esc(t.note||'')}</textarea></label><div class="full toolbar"><button class="btn primary" type="submit">${t.id?'儲存修改':'新增交易'}</button><button class="btn" id="cancelEdit" type="button">清空</button></div>`;}
  function renderTransactions(){const c=reconciledPortfolio(state);q('#transactions').innerHTML=`<div class="card"><h2>新增 / 修改交易</h2><form id="txForm" class="form-grid">${txForm()}</form></div><div class="table-wrap section"><table><thead><tr><th>#</th><th>倉位</th><th>日期</th><th>買賣</th><th>幣種</th><th>數量</th><th>金額U</th><th>本筆已實現</th><th>操作</th></tr></thead><tbody>${[...c.replay.history].reverse().map(t=>`<tr><td>${t.id}</td><td>${t.warehouse}</td><td>${t.date}</td><td>${t.side}</td><td>${t.asset}</td><td>${qty(t.qty)}</td><td>${fmt(t.amount)}</td><td>${t.side==='賣出'?signed(t.tradeRealized):'—'}</td><td><button data-edit="${t.id}">編輯</button> <button data-del="${t.id}">刪除</button></td></tr>`).join('')}</tbody></table></div>`;bindTx();}
  function bindTx(){const f=q('#txForm');f.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f)),id=d.id?+d.id:Math.max(0,...state.transactions.map(x=>x.id))+1,obj={id,warehouse:d.warehouse,exchange:d.exchange,date:d.date,side:d.side,asset:d.asset,price:+d.price||0,qty:+d.qty||0,amount:+d.amount||0,feeAsset:d.feeAsset,feeQty:+d.feeQty||0,costAdjustment:d.costAdjustment===''?null:+d.costAdjustment,reset:d.reset==='true',note:d.note||''},i=state.transactions.findIndex(x=>x.id===id);i>=0?state.transactions[i]=obj:state.transactions.push(obj);saveState(state);renderAll();switchTab('transactions');};q('#cancelEdit').onclick=()=>renderTransactions();qa('[data-edit]').forEach(b=>b.onclick=()=>{const t=state.transactions.find(x=>x.id===+b.dataset.edit);q('#txForm').innerHTML=txForm(t);bindTx();scrollTo({top:0,behavior:'smooth'});});qa('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('刪除這筆交易？')){state.transactions=state.transactions.filter(x=>x.id!==+b.dataset.del);saveState(state);renderAll();switchTab('transactions');}});}

  function renderPrices(){q('#prices').innerHTML=`<div class="card"><h2>價格</h2><div class="table-wrap"><table><thead><tr><th>資產</th><th>價格U</th></tr></thead><tbody>${assets.filter(a=>!['CASH','STABLE','OTHER'].includes(a)).map(a=>`<tr><td>${a}${a==='ETH'?'<span class="subtle">（WBETH 併入 ETH 曝險）</span>':''}</td><td><input data-price="${a}" type="number" step="any" value="${state.prices[a]||0}"></td></tr>`).join('')}</tbody></table></div></div>`;qa('[data-price]').forEach(i=>i.onchange=()=>{state.prices[i.dataset.price]=+i.value||0;saveState(state);renderAll();switchTab('prices');});}
  function renderBackup(){q('#backup').innerHTML=`<div class="card"><h2>備份 / 設定</h2><p>資料分層：records.js 記錄、calculations.js 計算、display.js 顯示。</p><div class="toolbar"><button class="btn" id="exportJson">匯出 JSON</button><label class="btn">匯入 JSON<input id="importJson" type="file" accept="application/json" hidden></label><button class="btn" id="resetData">重設為目前基準資料</button></div></div>`;q('#exportJson').onclick=()=>exportBackup(state);q('#importJson').onchange=async e=>{if(e.target.files[0]){const s=await importBackup(e.target.files[0]);saveState(s);setState(s);location.reload();}};q('#resetData').onclick=()=>{if(confirm('重設為目前基準資料？')){const s=resetState(seed);setState(s);location.reload();}};}
  function renderAll(){renderDashboard();renderTransactions();renderPlans();renderPrices();renderBackup();}
  q('#refreshPrices').onclick=async()=>{const pairs={BTC:'BTCUSDT',ETH:'ETHUSDT',BNB:'BNBUSDT',ADA:'ADAUSDT',SOL:'SOLUSDT'};for(const[a,symbol]of Object.entries(pairs)){try{const r=await fetch(`https://api.binance.com/api/v3/ticker/price?symbol=${symbol}`);const j=await r.json();if(+j.price)state.prices[a]=+j.price;}catch{}}saveState(state);renderAll();};
  renderAll();
}
