const SESSION_KEY='cryptoPortfolioEditUnlocked';
const PBKDF2_ITERATIONS=210000;
const SALT_HEX='15fca5195d7f63539ea2fc63af0e6669';
const EXPECTED_HASH_HEX='f6c49c6b38a2818b1c54913d23871b98773cf69fa4817962693065bc92763112';
const hexToBytes=hex=>new Uint8Array(hex.match(/.{1,2}/g).map(x=>parseInt(x,16)));
const bytesToHex=bytes=>[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');
const isUnlocked=()=>sessionStorage.getItem(SESSION_KEY)==='1';
async function verifyPassword(password){const keyMaterial=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:hexToBytes(SALT_HEX),iterations:PBKDF2_ITERATIONS,hash:'SHA-256'},keyMaterial,256);return bytesToHex(bits)===EXPECTED_HASH_HEX;}
function ensureModal(){let modal=document.querySelector('#editLockModal');if(modal)return modal;modal=document.createElement('div');modal.id='editLockModal';modal.className='edit-lock-modal hidden';modal.innerHTML=`<div class="edit-lock-dialog"><div class="edit-lock-title">解鎖編輯</div><div class="edit-lock-desc">輸入編輯密碼後，本分頁工作階段可修改交易、投資計畫、資金帳本與資產設定。密碼不會儲存在瀏覽器。</div><input id="editLockPassword" type="password" inputmode="numeric" autocomplete="current-password" placeholder="編輯密碼"><div id="editLockError" class="edit-lock-error"></div><div class="edit-lock-actions"><button class="btn" id="editLockCancel" type="button">取消</button><button class="btn primary" id="editLockConfirm" type="button">解鎖</button></div></div>`;document.body.appendChild(modal);modal.querySelector('#editLockCancel').onclick=()=>closeModal();modal.addEventListener('click',e=>{if(e.target===modal)closeModal();});modal.querySelector('#editLockConfirm').onclick=submitPassword;modal.querySelector('#editLockPassword').addEventListener('keydown',e=>{if(e.key==='Enter')submitPassword();});return modal;}
function openModal(){const modal=ensureModal();modal.classList.remove('hidden');const input=modal.querySelector('#editLockPassword');input.value='';modal.querySelector('#editLockError').textContent='';setTimeout(()=>input.focus(),0);}function closeModal(){document.querySelector('#editLockModal')?.classList.add('hidden');}
async function submitPassword(){const modal=ensureModal(),input=modal.querySelector('#editLockPassword'),error=modal.querySelector('#editLockError'),button=modal.querySelector('#editLockConfirm');button.disabled=true;error.textContent='驗證中…';try{if(await verifyPassword(input.value)){sessionStorage.setItem(SESSION_KEY,'1');closeModal();updateLockButton();}else{error.textContent='密碼錯誤';input.select();}}finally{button.disabled=false;}}
function lock(){sessionStorage.removeItem(SESSION_KEY);updateLockButton();}
function updateLockButton(){let btn=document.querySelector('#editLockButton');if(!btn){btn=document.createElement('button');btn.id='editLockButton';btn.className='btn edit-lock-button';const top=document.querySelector('.top'),refresh=document.querySelector('#refreshPrices');if(refresh?.parentElement===top)top.insertBefore(btn,refresh);else top?.appendChild(btn);btn.onclick=()=>isUnlocked()?lock():openModal();}btn.textContent=isUnlocked()?'🔓 編輯已解鎖':'🔒 唯讀';btn.classList.toggle('unlocked',isUnlocked());}
function isProtectedTarget(target,eventType){if(!(target instanceof Element))return false;if(target.closest('#editLockModal,#editLockButton'))return false;if(target.closest('#transactions')){if(eventType==='submit'&&target.closest('#txForm'))return true;if(target.closest('[data-edit],[data-del],#txForm button,#txForm input,#txForm select,#txForm textarea'))return true;}if(target.closest('#plans')&&target.closest('input,button,select,textarea'))return true;if(target.closest('#ledger')&&target.closest('input,button,select,textarea'))return true;if(target.closest('#settingsAdmin')&&target.closest('input,button,select,textarea'))return true;if(target.matches('#importJson,#resetData')||target.closest('#resetData'))return true;return false;}
for(const type of ['click','change','input','submit'])document.addEventListener(type,e=>{if(isUnlocked()||!isProtectedTarget(e.target,type))return;e.preventDefault();e.stopImmediatePropagation();openModal();},true);
document.addEventListener('DOMContentLoaded',()=>{ensureModal();updateLockButton();});window.cryptoPortfolioEditLock={isUnlocked,open:openModal,lock};