import {loadRemoteSettings,saveAssetSetting,saveLocationSetting} from './supabase-data.js?v=20260911-1718';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unlocked=()=>window.cryptoPortfolioEditLock?.isUnlocked?.()??sessionStorage.getItem('cryptoPortfolioEditUnlocked')==='1';
const askUnlock=()=>window.cryptoPortfolioEditLock?.open?.();
let settings=null,mounting=false;

function ensureStyle(){if(document.querySelector('#settingsAdminStyles'))return;const s=document.createElement('style');s.id='settingsAdminStyles';s.textContent='.settings-admin-grid{display:grid;grid-template-columns:1fr;gap:16px}.settings-admin-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.settings-admin-head h2{margin:0}.settings-admin-form{margin-top:14px}.settings-admin-form .toolbar{align-items:center}.settings-admin-status{font-size:12px}.settings-admin-table td,.settings-admin-table th{white-space:nowrap}.settings-admin-table td:nth-child(2),.settings-admin-table td:nth-child(3){white-space:normal}@media(min-width:1050px){.settings-admin-grid{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
const assetForm=(a={})=>`<form id="assetSettingForm" class="form-grid settings-admin-form"><input type="hidden" name="originalCode" value="${esc(a.code||'')}"><label><span>代號</span><input name="code" value="${esc(a.code||'')}" placeholder="例如 BTC" ${a.code?'readonly':''}></label><label><span>顯示名稱</span><input name="displayName" value="${esc(a.displayName||'')}"></label><label><span>行情 Symbol</span><input name="priceSymbol" value="${esc(a.priceSymbol||'')}" placeholder="留空自動 CODEUSDT"></label><label><span>排序</span><input name="sortOrder" type="number" value="${a.sortOrder??100}"></label><label><span>介面顯示</span><select name="enabled"><option value="true" ${a.enabled!==false?'selected':''}>啟用</option><option value="false" ${a.enabled===false?'selected':''}>停用</option></select></label><label><span>自動行情</span><select name="priceEnabled"><option value="true" ${a.priceEnabled!==false?'selected':''}>啟用</option><option value="false" ${a.priceEnabled===false?'selected':''}>停用</option></select></label><label class="full"><span>備註</span><input name="note" value="${esc(a.note||'')}"></label><div class="full toolbar"><button type="button" class="btn" id="assetSettingCancel">清空</button><button type="submit" class="btn primary">${a.code?'儲存資產':'新增資產'}</button></div></form>`;
const locationForm=(l={})=>`<form id="locationSettingForm" class="form-grid settings-admin-form"><input type="hidden" name="id" value="${esc(l.id||'')}"><label><span>名稱</span><input name="label" value="${esc(l.label||'')}" placeholder="例如 Kraken / 綠葉"></label><label><span>類型</span><select name="type">${[['exchange','交易所'],['wallet','錢包'],['platform','外部平台'],['external','外部資金'],['other','其他']].map(([v,n])=>`<option value="${v}" ${l.type===v?'selected':''}>${n}</option>`).join('')}</select></label><label><span>排序</span><input name="sortOrder" type="number" value="${l.sortOrder??100}"></label><label><span>介面顯示</span><select name="enabled"><option value="true" ${l.enabled!==false?'selected':''}>啟用</option><option value="false" ${l.enabled===false?'selected':''}>停用</option></select></label><label class="full"><span>備註</span><input name="note" value="${esc(l.note||'')}"></label><div class="full toolbar"><button type="button" class="btn" id="locationSettingCancel">清空</button><button type="submit" class="btn primary">${l.id?'儲存位置':'新增位置'}</button></div></form>`;
function render(){const host=document.querySelector('#backup');if(!host||!settings)return;document.querySelector('#settingsAdmin')?.remove();ensureStyle();const wrap=document.createElement('div');wrap.id='settingsAdmin';wrap.className='settings-admin-grid section';const assets=[...settings.assets].sort((a,b)=>a.sortOrder-b.sortOrder),locations=[...settings.locations].sort((a,b)=>a.sortOrder-b.sortOrder);wrap.innerHTML=`<div class="card"><div class="settings-admin-head"><h2>資產管理</h2><span class="subtle">停用只會從新操作介面隱藏</span></div><div id="assetSettingFormWrap">${assetForm()}</div><div class="table-wrap section settings-admin-table"><table><thead><tr><th>狀態</th><th>代號</th><th>名稱</th><th>行情 Symbol</th><th>排序</th><th>操作</th></tr></thead><tbody>${assets.map(a=>`<tr><td>${a.enabled?'啟用':'停用'}</td><td>${esc(a.code)}</td><td>${esc(a.displayName)}</td><td>${esc(a.priceSymbol||'—')}</td><td>${a.sortOrder}</td><td><button data-asset-edit="${esc(a.code)}">編輯</button> <button data-asset-toggle="${esc(a.code)}">${a.enabled?'停用':'啟用'}</button></td></tr>`).join('')}</tbody></table></div></div><div class="card"><div class="settings-admin-head"><h2>位置 / 交易所管理</h2><span class="subtle">交易所、錢包、放貸平台都在這裡</span></div><div id="locationSettingFormWrap">${locationForm()}</div><div class="table-wrap section settings-admin-table"><table><thead><tr><th>狀態</th><th>名稱</th><th>類型</th><th>排序</th><th>操作</th></tr></thead><tbody>${locations.map(l=>`<tr><td>${l.enabled?'啟用':'停用'}</td><td>${esc(l.label)}</td><td>${esc(l.type)}</td><td>${l.sortOrder}</td><td><button data-location-edit="${esc(l.id)}">編輯</button> <button data-location-toggle="${esc(l.id)}" ${l.id==='external'?'disabled':''}>${l.enabled?'停用':'啟用'}</button></td></tr>`).join('')}</tbody></table></div></div>`;host.appendChild(wrap);bind()}
function requireUnlock(){if(unlocked())return true;askUnlock();return false}
async function reload(){settings=await loadRemoteSettings();render()}
function bind(){const assetWrap=document.querySelector('#assetSettingFormWrap'),locationWrap=document.querySelector('#locationSettingFormWrap');const bindAsset=()=>{const f=document.querySelector('#assetSettingForm');if(!f)return;f.code.addEventListener('input',()=>{if(!f.priceSymbol.value)f.priceSymbol.placeholder=`${f.code.value.trim().toUpperCase()}USDT`});f.onsubmit=async e=>{e.preventDefault();if(!requireUnlock())return;const d=Object.fromEntries(new FormData(f));const code=String(d.code||'').trim().toUpperCase();await saveAssetSetting({code,displayName:d.displayName||code,enabled:d.enabled==='true',priceEnabled:d.priceEnabled==='true',priceSource:'binance_spot',priceSymbol:d.priceSymbol||`${code}USDT`,sortOrder:+d.sortOrder||100,note:d.note||''});await reload();location.reload()};document.querySelector('#assetSettingCancel').onclick=()=>{assetWrap.innerHTML=assetForm();bindAsset()}};const bindLocation=()=>{const f=document.querySelector('#locationSettingForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();if(!requireUnlock())return;const d=Object.fromEntries(new FormData(f));const id=d.id||`loc-${Date.now()}`;await saveLocationSetting({id,label:d.label||id,type:d.type,enabled:d.enabled==='true',sortOrder:+d.sortOrder||100,note:d.note||''});await reload();location.reload()};document.querySelector('#locationSettingCancel').onclick=()=>{locationWrap.innerHTML=locationForm();bindLocation()}};bindAsset();bindLocation();document.querySelectorAll('[data-asset-edit]').forEach(b=>b.onclick=()=>{const a=settings.assets.find(x=>x.code===b.dataset.assetEdit);assetWrap.innerHTML=assetForm(a);bindAsset();assetWrap.scrollIntoView({behavior:'smooth',block:'center'})});document.querySelectorAll('[data-asset-toggle]').forEach(b=>b.onclick=async()=>{if(!requireUnlock())return;const a=settings.assets.find(x=>x.code===b.dataset.assetToggle);await saveAssetSetting({...a,enabled:!a.enabled});await reload();location.reload()});document.querySelectorAll('[data-location-edit]').forEach(b=>b.onclick=()=>{const l=settings.locations.find(x=>x.id===b.dataset.locationEdit);locationWrap.innerHTML=locationForm(l);bindLocation();locationWrap.scrollIntoView({behavior:'smooth',block:'center'})});document.querySelectorAll('[data-location-toggle]').forEach(b=>b.onclick=async()=>{if(!requireUnlock())return;const l=settings.locations.find(x=>x.id===b.dataset.locationToggle);if(!l||l.id==='external')return;await saveLocationSetting({...l,enabled:!l.enabled});await reload();location.reload()})}
async function mount(){if(mounting)return;const host=document.querySelector('#backup');if(!host||document.querySelector('#settingsAdmin'))return;mounting=true;try{settings=await loadRemoteSettings();render()}catch(err){console.error('Settings admin failed.',err)}finally{mounting=false}}
new MutationObserver(()=>mount()).observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('load',mount);mount();
